### ISSUE TITLE
Doesn't work with cwd

### ISSUE THREAD

**Issue by rightaway** [mskelton/yarn-plugin-outdated#55]
`yarn --cwd dir outdated` doesn't run the command from dir. You have to already be in dir or it says `Outdated lockfile. Please run yarn install and try again.` It should use cwd to be consistent with other yarn commands.

**Comment by mskelton** [comment]
Could you share a reproducible example?  It's working for me with my testing.

**Comment by rightaway** [comment]
It was caused by yarn 1 being set globally. With the right version it works.

**Comment by rightaway** [comment]
@mskelton Is it working in 4.1.1? You can't be in the directory when you test.

```
Usage Error: Couldn't find a script named "outdated".

$ yarn run [--inspect] [--inspect-brk] [-T,--top-level] [-B,--binaries-only] [--require #0] <scriptName> ...
```

**Comment by mskelton** [comment]
@rightaway The plugin is definitely working. More than likely you don't have it installed in the project you are trying to use it with.

**Comment by rightaway** [comment]
I tried `yarn --cwd /project outdated`

`/project/.yarnrc.yml` has nodeLinker can you try it with that?

```
nodeLinker: node-modules
plugins:
  - checksum: 53df621960dbcb9cc3953b45376e0d7e0fbcb870eec71ebb8ffa575c2e834349fdcfa255c46b8fa3fff2c65f26e55c7339c2cb57ee80f92d62c9e181bcb7792d
    path: .yarn/plugins/@yarnpkg/plugin-outdated.cjs
    spec: "https://mskelton.dev/yarn-outdated/v4"
```

`/project/.yarn/plugins/@yarnpkg/plugin-outdated.cjs` has sha 512 that matches checksum in .yarnrc.

I think I installed it correctly is there anything else I need to do?
